[package]
authors = ['Kai Schmidt <kaikaliischmidt@gmail.com>']
edition = '2018'
name = 'bimo'
version = '0.1.0'

[dependencies]
clap.features = ['derive']
clap.version = '3.0.0-beta.2'
color-backtrace = '0.5'
itertools = '0.10'
once_cell = '1.8.0-pre.1'
pest = '2'
pest_derive = '2'
seahash = '4'
